name: ${project.artifactId}
main: net.kaikk.mc.serverredirect.bukkit.ServerRedirect
version: ${project.version}
author: ${developer}
api-version: 1.13
softdepend: [PlaceholderAPI]

commands:
   serverredirect:
      aliases: [redirect]
      permission: serverredirect.command.redirect
   fallbackserver:
      aliases: [fallback]
      permission: serverredirect.command.fallback
   ifplayercanredirect:
      permission: serverredirect.command.ifplayercanredirect
   ifplayercannotredirect:
      permission: serverredirect.command.ifplayercannotredirect
